Datadog Source Code Integration
open-telemetry/opentelemetry-rust-contrib pull request #20
Opened 2023-12-17 11:52 UTC by Hartigan

## Changes

This pull request introduces part of  [Datadog Source Code Integration](https://docs.datadoghq.com/integrations/guide/source-code-integration/?tab=go)
Added compile time env variables: `DD_GIT_REPOSITORY_URL` and `DD_GIT_COMMIT_SHA`. Exporter will send this information in sampled traces.

## Example of usage

```
DD_GIT_REPOSITORY_URL="git@github.com:Hartigan/opentelemetry-rust-contrib.git" DD_GIT_COMMIT_SHA="e4b2b10970d10237457a3d1a87a3e75cf41488ad" cargo build
```

2023-12-17 18:49 UTC, lalitb approved these changes

2023-12-18 05:39 UTC, TommyCpp commented on opentelemetry-datadog/src/exporter/model/v05.rs
> +            const GIT_META_TAGS_COUNT: u32 = if matches!((option_env!("DD_GIT_REPOSITORY_URL"), option_env!("DD_GIT_COMMIT_SHA")), (Some(_), Some(_))) { 2 } else { 0 };
nit: can we move this to top of the file with other constant?

2023-12-18 05:50 UTC, TommyCpp reviewed
One nit

2023-12-18 10:00 UTC, hdost requested changes
Looks good, just @TommyCpp's request please.

2023-12-19 03:18 UTC, hdost approved these changes

2023-12-19 03:56 UTC, merged