Fix main readme to be consistent with main repo
open-telemetry/opentelemetry-rust-contrib pull request #77
Opened 2024-06-07 14:52 UTC by cijothomas

Fixes #
Design discussion issue (if applicable) #

## Changes

Please provide a brief description of the changes here.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

2024-06-07 16:35 UTC, lalitb approved these changes
Thanks for cleanup

2024-06-12 07:44 UTC, hdost requested changes
I think it looks good, just the suggested commits lalit had.

2024-06-17 20:44 UTC, cijothomas commented on README.md
>  ## Supported Rust Versions
keeping this now, will revisit to have better wording here.

2024-06-17 20:48 UTC, lalitb approved these changes

2024-06-17 20:48 UTC, lalitb commented
LGTM with the updates. Thanks.

2024-06-17 20:53 UTC, merged

2024-06-17 20:54 UTC, cijothomas commented
@hdost Please share any additional feedback and will address them in subsequent PRs. I dismissed review to unblock merge.