opentelemetry-resource-detectors: add `LambdaResourceDetector`
open-telemetry/opentelemetry-rust-contrib pull request #93
Opened 2024-07-22 14:30 UTC by thomasgouveia

## Changes

This PR introduces the `LambdaResourceDetector`, which can detect resource attributes from an AWS Lambda environment. A new feature flag has been introduced `aws-lambda` to hide this code when it is not needed.

It is based on the [Go implementation](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/detectors/aws/lambda).

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

2024-07-22 14:36 UTC, cijothomas requested changes
Thanks for your contribution. I'd request to make this either a standalone crate in this repo, or part of https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-aws

We want to keep any platform specific (AWS/Azure/GCP etc.) outside of the detectors to better ensure ownership, maintenance in the future.

2024-07-22 14:40 UTC, thomasgouveia commented
Hi @cijothomas , no problem, I understand and agree with that vision. What do you think of adding a detector module under `opentelemetry-aws`?

2024-07-22 16:29 UTC, cijothomas commented
> Hi @cijothomas , no problem, I understand and agree with that vision. What do you think of adding a detector module under `opentelemetry-aws`? Or should detectors be part of an external crate, such `opentelemetry-aws-resource-detectors` ?

I am unsure if there is any owner for `opentelemetry-aws`, as it was ported over from the main repo to this repo. We haven't yet established a process for allowing people to own individual crates. I think its best to start by putting detectors inside `opentelemetry-aws` crate itself for now. (Once we establish a more formal process for ownership, we can extract it to own crate, should the future owners decide to)

2024-07-22 19:11 UTC, thomasgouveia commented
@cijothomas Ok LGTM. I'll do it asap. Thanks!

2024-07-23 07:42 UTC, lalitb approved these changes

2024-07-26 16:59 UTC, cijothomas approved these changes

2024-07-26 16:59 UTC, merged